### ISSUE TITLE
Bump version in `--version` command

### ISSUE THREAD

**Issue by kuhball** [wobcom/transceiver-exporter#8]
Hi, 

would it be possible to bump the version corresponding to the release version within github in [main.go](https://github.com/wobcom/transceiver-exporter/blob/main/main.go#L16) ? We're using ansible to roll out the exporter and are checking if the installed version is matching the desired version. Thanks for providing this exporter :)

**Comment by johannwagner** [comment]
Whoops, of course! Will provide a fix tomorrow, I am out of office today :/
